server:
  port: 8080

logging:
  level:
    root: INFO

ecowatt-api:
  base-url: "https://digital.iservices.rte-france.com"
  encoded-credentials: ${ECOWATT_API_ENCODED_CREDENTIALS:}
  sandbox-mode: ${ECOWATT_API_SANDBOX_MODE:true}

email-api:
  email-sender: ${EMAIL_API_SENDER_EMAIL:}
  email-password: ${EMAIL_API_SENDER_PASSWORD:}
  email-host: "smtp.gmail.com"
  email-port: 587

send-ecowatt-email-task:
  target-email: ${EMAIL_TASK_TARGET_EMAIL:}
